# https://medium.com/@LihauTan/5-steps-to-build-nodejs-using-travis-ci-fd7bcd030106
notifications:
  email: false
language: node_js

os:
  - linux
  - osx
  - windows
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - npm install electron-packager -g
script:
  - npm install
  - electron-packager . UnicodePicker
