notifications:
  email: false
language: node_js

os:
  - linux
  - osx
  #- windows seems to have bugs
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - npm install electron-packager -g
script:
  - npm install
  - electron-packager . UnicodePicker
