# https://medium.com/@LihauTan/5-steps-to-build-nodejs-using-travis-ci-fd7bcd030106
language: node_js
node_js:
  - node
notifications:
  email: false
before_script:
  - npm install
script:
  - npm start
