# https://medium.com/@LihauTan/5-steps-to-build-nodejs-using-travis-ci-fd7bcd030106
notifications:
  email: false
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
script:
  - npm start
